import json
import os
import shutil

FACILITY_DIR = 'facility'

with open('index.json', 'r', encoding='utf-8') as f:
    facilities = json.load(f)

redirect_template = """\
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta http-equiv="refresh" content="0; url={new_filename}">
<link rel="canonical" href="{new_filename}">
<title>Redirecting...</title>
</head>
<body>
<p>Redirecting... <a href="{new_filename}">Click here if not redirected.</a></p>
</body>
</html>"""

updated = []

for facility in facilities:
    detloc = facility.get('DETLOC', '')
    old_filename = facility.get('filename', '')

    # Skip notes entry and any entry without a real DETLOC
    if not detloc or detloc == 'NOTES' or not old_filename:
        updated.append(facility)
        continue

    new_filename = f"{detloc}.html"

    if old_filename == new_filename:
        # Already using DETLOC name, nothing to do
        updated.append(facility)
        continue

    old_path = os.path.join(FACILITY_DIR, old_filename)
    new_path = os.path.join(FACILITY_DIR, new_filename)

    # Uppercase redirect stub name so it matches the fallback generated by
    # facilityNameToHtmlFile() on case-sensitive filesystems (e.g. GitHub Pages)
    base, ext = os.path.splitext(old_filename)
    redirect_filename = base.upper() + ext.lower()
    redirect_path = os.path.join(FACILITY_DIR, redirect_filename)

    if os.path.exists(old_path):
        if os.path.exists(new_path):
            print(f"SKIP (target exists): {old_filename} -> {new_filename}")
        else:
            shutil.move(old_path, new_path)
            print(f"Renamed : {old_filename} -> {new_filename}")

        # Create redirect stub at uppercase path
        with open(redirect_path, 'w', encoding='utf-8') as f:
            f.write(redirect_template.format(new_filename=new_filename))
        print(f"Redirect : {redirect_filename} -> {new_filename}")
    else:
        print(f"MISSING  : {old_path} (skipping)")

    facility['filename'] = new_filename
    updated.append(facility)

with open('index.json', 'w', encoding='utf-8') as f:
    json.dump(updated, f, indent=4, ensure_ascii=False)

print("\nDone. index.json updated.")
